---

- hosts: all
  become: true
  tasks:

  - name: update repos index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache server2
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: add php support for apache2 server
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

        
        
        
